import type { Metadata } from "next";
import "./../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Providers from "../components/Providers";
import { ColorModeScript } from "@chakra-ui/react";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="">
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <div>{children}</div>
            <div className="absolute bottom-0 left-0 bg-gray-600 w-full">
              <Footer />
            </div>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
