import type { Metadata } from "next";
import "./../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Providers from "../components/Providers";
import { ColorModeScript } from "@chakra-ui/react";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="h-screen">
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <ColorModeScript initialColorMode={"light"} />
            <div>{children}</div>
            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
